// data.js

export const categories = [
    "Abs",
    "Belt Drive",
    "Bearing Kit",
    "BSVI Products",
    "Brake Switch",
    "CDEI",
    "C.D.I",
    "Consumable Filters",
    "Drum / Drum Plate / Coupling Hub / Wheel Rim",
    "Electronic Relay",
    "Filters & Horn",
    "Footrest Bracket",
    "Other Products (Cylinder Kit / Fuse Blade)",
    "Flasher / Buzzer",
    "Floor Set / Speedo Gear",
    "Fuel Items",
    "Lever & Yoke",
    "Varroc Oil / Grease",
    "Handle Bar Switch / Handle Bar Weigth",
    "Ignition Coil",
    "Insulator For Carburetor",
    "Lighting Products",
    "Magneto Assembly & Spares",
    "Modular Switch",
    "Oring",
    "Other (Oil Pump Gear / Clutch Roller / Plug Cap)",
    "Oil Seal Kit",
    "Gaskets",
    "Rear View Mirror",
    "Regulator Rectifier (R.R.)",
    "Rubber Items",
    "Relay",
    "Switches / Locks",
    "Starter Moter & Spares",
    "Speedo Gear",
    "TPSR / Swing Arm Assly",
  ];
  
  export const vehicles = ["Auto", "Bike", "Car", "Scooter/Scooty", "Other"];
  